### ISSUE TITLE
Higher order terms in reaction rates

### ISSUE THREAD

**Issue by elevien** [JuliaDiffEq/DiffEqBiological.jl#1]
Should the rates produced by `build_jumps_from_reaction` be modified for higher order reactions?  For example, see the table on page 5 of [this paper](http://projecteuclid.org/euclid.aoap/1360682022).

**Comment by ChrisRackauckas** [comment]
Well, by a quirk of implementation, you can have reactants like `[1,2,2]` and that should be x_1 * x_2^2, so it technically is implemented, but the API probably should be improved to support this better. 

Another thing which should be supported are Hill functions.

**Comment by elevien** [comment]
But there is no way to produce `x_1*(x_1-1)`. In chemical reaction network theory this would correspond to the reaction `2*A -> B`, for example. More generally, one usually considers rates of the form
<img width="409" alt="screen shot 2017-02-27 at 6 17 31 pm" src="https://cloud.githubusercontent.com/assets/19657477/23387330/13cb0d56-fd19-11e6-8de5-285680256b5d.png">
where `nu` contains the stoichiometry. Currently, what is produced are the leading order terms when these rates are expanded in terms of a volume factor.  Should such rates be implemented, or is it too specific to chemical kinetics?

**Comment by ChrisRackauckas** [comment]
>Should such rates be implemented, or is it too specific to chemical kinetics?

I think this should definitely be implemented, since this package is just for biological models such as this and chemical kinetics is a huge thing (which I myself am interested in). The real question is, how do we get that kind of generality without sacrificing ease of use? The hard part is coming up with a good API. Right now, declaring reactions is very simple. It would be good to try to keep the simplicity while making it more powerful.

**Comment by elevien** [comment]
> The real question is, how do we get that kind of generality without sacrificing ease of use?

How do feel about making a few different `Reaction` types? For example, the `Reaction` that is currently implemented could be renamed `ReactionRateReaction` because it corresponds to the standard reaction rate equations. Then we could implement  `MassActionRateReaction` which in addition to taking the stoichiometry, also takes a scaling exponent and a volume factor. 

A related issue is how to design a nice interface for constructing spatial problems. Maybe a  `Diffusion` type that takes a mesh as an argument?

**Comment by ChrisRackauckas** [comment]
>How do feel about making a few different Reaction types? For example, the Reaction that is currently implemented could be renamed ReactionRateReaction because it corresponds to the standard reaction rate equations. Then we could implement MassActionRateReaction which in addition to taking the stoichiometry, also takes a scaling exponent and a volume factor.

That sounds reasonable. I also want to find out how to make the same reactions generate SDEs and ODEs as well, to make it easy to switch between model types. Maybe those should just be different types, but define conversions between them? Or maybe a `build_ode_from_reactions` function?

>A related issue is how to design a nice interface for constructing spatial problems. Maybe a Diffusion type that takes a mesh as an argument?

That takes a whole different thing since now you have to get a spatial discretization involved. For space in discrete models, I'm not sure about the easy way to do that "automatically".

**Comment by elevien** [comment]
>  I also want to find out how to make the same reactions generate SDEs and ODEs as well, to make it easy to switch between model types.

I agree, switching between model types is very important. Maybe there should be a `ChemicalReactionNetwork` type that contains the stoichiometry, but has no information about the dynamics. Then various methods could build the actual problems. For example, something like `ReactionRateProblem(network,parameters,tspan)` would give you an ODE problem. Personally, I like this approach because it is consistent with how I think of these things mathematically. 

BTW, once we settle on what exactly needs to be done, I'm happy to open a PR.

**Comment by ChrisRackauckas** [comment]
This is an interesting related read. The general form should be covered by what we're discussing.

http://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1004012

**Comment by ChrisRackauckas** [comment]
Solved by https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/7
