### ISSUE TITLE
Higher order terms

### ISSUE THREAD

**Issue by J-Revell** [JuliaDiffEq/DiffEqBiological.jl#10]
In relation to https://github.com/JuliaDiffEq/DiffEqBiological.jl/issues/1 & my own issues when testing a simple model, I am not sure https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/7 is entirely correct. 

For a true, stochastic, second order reaction with 2 molecules of the same species reacting with each other the reaction rate is 
k*u[1]*(u[1]-1) / 2!, 
and not 
k*u[1]*(u[1]-1).

In the case of 3 molecules the rate would be 
k*u[1]*(u[1]-1)*(u[1]-2) / 3!.

This is because the number of ways of pairing 2 molecules of the same species (using binomial coefficients) is 
u[1]! / (2! * (u[1]-2)!). 
For N molecules this generalizes to 
u[1]! / (N! * (u[1]-N)!). 
This is a key difference between deterministic and stochastic kinetics. 

They apply these corrections in the previously mentioned article, http://stochpy.sourceforge.net/html/userguide_doc.html#stochastic-rate-equations, although without explaining where the constant 0.5 comes from. (Likewise the constant 1/6 in the 3rd order example 3 comes from the factor 1/3!)

There is more information in the original Gillespie papers (e.g. eq 6a in http://www.phys.ufl.edu/~hagen/Readings/gillespie_1977.pdf)

**Comment by J-Revell** [comment]
I suppose there may be cases where this could be undesirable(?), in which case it is easy enough for the user to manually convert rate_constants as a workaround.

I have just realised that a second problem that was causing me issues was that the @reaction_network syntax does not create the mapping to support the u[1]*(u[1]-1) (or even u[1]*u[1]) propensity calculations. 

e.g. when using `@reaction_network` a reaction 2A+B->C generates (1,2) as the reactants instead of (1,1,2).

The macro has to be used with care at the moment!

**Comment by alanderos91** [comment]
@J-Revell: I tried running:
```
r = @reaction_network begin
  2.0, 2A + B --> C
end
```
This produces reactants `(1,2)`, identified with `A` and `B`, and `((1,-2),(2,-1),(3,1))` for the net stoichiometries of `A`, `B`, and `C`, respectively (see `r.reactions.reactants` and `r.reactions.stoichiometry`).

If I understand correctly, you are pointing out that the macro fails to capture some information required by `Reaction`? At the moment, I can't seem to access the documentation to see how it is intended work.

**Comment by ChrisRackauckas** [comment]
@J-Revell is right that the way that the rate is written:

https://github.com/JuliaDiffEq/DiffEqBiological.jl/blob/master/src/reactions.jl#L66-L76

it only takes into account 1 of reactant `A`, so that's giving `k*u[1]`. It might be better to do away with `reactants` and just loop through `stoichiometry`. `for i in eachindex(r.stoichiometry)`, then the reactant is just `reactant = r.stoichiometry[i][1]` and the `k` is `maximum(-r.stoichiometry[i][2],0)` (since it's negative for reactants). Then there should just be an inner loop `j=1:k` that does `prod *= u[reactant]-j`. With Julia v0.7 the literal 1s and 2s should fold in at compile time (along with some other IPO gains), so I don't think that making the rates work on `stoichiometry` will have have a performance effect either once those compiler optimizations are live. Then we just need to remember to divide by `k!`.

**Comment by ChrisRackauckas** [comment]
I realized that we need to be smart about this somehow. We don't always want to apply higher order term handling for example if `u[i]` is a continuous value from an ODE that represents a concentration instead of a discrete amount. Somehow this needs a toggle.

**Comment by ChrisRackauckas** [comment]
@J-Revell see #15. We are re-doing the DSL and it would be good to get this right.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/15
