### ISSUE TITLE
Symbolic calculations à la ParameterizedFunctions

### ISSUE THREAD

**Issue by korsbo** [JuliaDiffEq/DiffEqBiological.jl#14]
Wouldn't it be nice if we could provide fields with symbolically calculated jacobians, etc., like in ParameretizedFunctions?

Me and @Gaussia are already working on implementing this, but we are unsure of how to best realise the idea. It should be pretty straightforward to actually get the things calculated (with heavy inspiration from ParameterizedFunctions.jl) but I'm wondering how to best present the available expressions to the problem/solver. 

The `Reaction` type that we are working on has a field for a function with the ODE. Let's say that we have an instance of the `Reaction` type called `r`. The ODE will be available as `r.f`. Would it be best to place the symbolically calculated stuff in separate fields of `r`, or should we just make `r.f` a subtype of AbstractParameterizedFunctions and place all the stuff in there (e.g.  `r.f.symjac`). 

And if not, what do we need to overload in order for the DEProblem/solver to know that the jacobian, etc., exists?

**Comment by ChrisRackauckas** [comment]
>Would it be best to place the symbolically calculated stuff in separate fields of r, or should we just make r.f a subtype of AbstractParameterizedFunctions and place all the stuff in there (e.g. r.f.symjac).

It wouldn't really matter since the documented interface only touches the overloaded functions. But with this in mind, you should probably be aware of some of the next major steps we are doing. We will be using a function type in the near future:

https://github.com/JuliaDiffEq/DiffEqBase.jl/issues/52

and essentially `ODEProblem` with a normal `f` will wrap into a `DiffEqFunction`. These will have a defined interface for grabbing Jacobians and such from fields (because technically the trait-based system we use could be incorrect in some weird edge cases). In that sense, you might want to build this so that way it can be an `AbstractDiffEqFunction` when that happens, i.e. put the things as fields.

One other thing to be aware of is DiffEqDSL, which was workshopped here:

https://github.com/JuliaDiffEq/ParameterizedFunctions.jl/issues/17

For now, I guess aim at ParameterizedFunctions.jl, but as noted here:

https://github.com/JuliaDiffEq/DiffEqDSL.jl/issues/1

I do want to build a more comprehensive DSL to replace ParameterizedFunctions.jl sometime in the future (though the first would still be supported for quite some time). If in order to massage this around you need to be building parts of this DSL anyways, we might as well just get this started. And BTW if you know of any students we can make this a funded Google Summer of Code project (or outside funding). I really want to get this off the ground sooner rather than later. From this DSL things like Jacobians and such would be calculated too.

>And if not, what do we need to overload in order for the DEProblem/solver to know that the jacobian, etc., exists?

http://docs.juliadiffeq.org/latest/features/performance_overloads.html

**Comment by korsbo** [comment]
Thanks for your insightful and informative answer! I will see if I can easily hijack parts of ParameterizedFunctions.jl, otherwise I may leave the symbolic stuff for later (my professor would not likely be impressed by my spending too much time on this).

But I still have one question which relates all the changes that me and @Gaussia are doing: what is your stance on changes to the API? Currently, we have a reaction macro which is similar to `@ode_def`:


![reaction_network_demo](https://user-images.githubusercontent.com/16306680/35967115-d1d85cfa-0cb7-11e8-94a7-457cf9f58942.png)

This change in API allows the user to create function overloads for `MyType`, it removes the problem of inferring parameter symbols and order, and it follows the syntax of `@ode_def`. We could limit ourselves to the previous syntax, but I find this one to be better. 

What say ye?

**Comment by ChrisRackauckas** [comment]
Please expand the syntax as necessary. Something like that will likely have to be done, and what you've chosen looks pretty clean.

**Comment by korsbo** [comment]
Cool, the proposed update can be found in @Gaussia's PR. The symbolic Jac is calculated but currently not used. We could postpone that particular issue until we have figured out how to merge the new with the old.

**Comment by ChrisRackauckas** [comment]
Let's revive this.

**Comment by korsbo** [comment]
Ok, I can think of the following steps that needs to be done:

- convert the already calculated jacobian to expressions.
- copy more symbolic calculations and expression conversions from ParameterizedFunctions.jl
- overload reaction_network.f with the correct stuff.

will the last point be sufficient for the solver to be able to use them, or is that only for functions which are subtypes of AbstractParameterizedFunctions?

**Comment by ChrisRackauckas** [comment]
>will the last point be sufficient for the solver to be able to use them, or is that only for functions which are subtypes of AbstractParameterizedFunctions?

That's sufficient.

**Comment by korsbo** [comment]
This would basically mean a copy-paste of half of ParameterizedFunctions.jl. One thing to consider is whether we instead should rework ParameterizedFunctions a bit, such that we can just call one of its functions rather than copy-pasting.

`ode_def_opt` is a massive function, half of which we want. If we could split it into `parse_ode_def`, `generate_support_functions` and `generate_output_expression` then we could just import and call `generate_support_functions`.

**Comment by isaacsas** [comment]
@korsbo I think we've now got this covered? Ok to close?
