### ISSUE TITLE
Add inbounds on the rate functions

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/DiffEqBiological.jl#29]

**Comment by Gaussia** [comment]
Care to clarify for one that is not exactly sure what you mean?

**Comment by ChrisRackauckas** [comment]
`@inbounds A[i]` speeds up indexing, and I don't think it's applied in the current setup.

**Comment by Gaussia** [comment]
There was a commit relating to this 9 days ago (by @ChrisRackauckas ). Did that properly fix this issue, which in that case can be dropped.

**Comment by ChrisRackauckas** [comment]
That did it for the `affect!` functions, but not the rate functions.

**Comment by Gaussia** [comment]
Good. I think I know what more we need to do (at least how to do it). However I would like to double check before I start messing around, to avoid the troubles if I am wrong. I think I understand what the advantage with adding this is, but I am far from familiar with the concept.

- Currently the `@inbounds` is added in the jump_affect_expression (which is saved in the datastructure so that it can be checked/used/printed/whatever. It is possible to move `@inbounds` so that it is a part of the final function declaration, but not a part of the saved expression structure.

- Is there an advantage of having `@inbounds` in the `f` and `g` used for ODEs/SDEs?

- I will add it to the rate function so that it will look something like
```julia
(u,p,t) -> @inbounds p[1]*u[1]*u[2]
```
is that right?

**Comment by ChrisRackauckas** [comment]
>It is possible to move @inbounds so that it is a part of the final function declaration, but not a part of the saved expression structure.

Yes. Just do `@inbounds begin` around the whole expression inside of the function.

>Is there an advantage of having @inbounds in the f and g used for ODEs/SDEs?

Yes, it would give a performance advantage and allow more compiler optimizations. It's hard to know how much and depends on the model.

>I will add it to the rate function so that it will look something like

**Comment by isaacsas** [comment]
Should be closed by [103](https://github.com/JuliaDiffEq/DiffEqBiological.jl/pull/103)
