### ISSUE TITLE
@reaction network ODE solver

### ISSUE THREAD

**Issue by MahdiarSadeghi** [JuliaDiffEq/DiffEqBiological.jl#51]
I am stock with an unreasonable solution that I get from Julia ode solver. You might be the right person to ask this. Would you please take a look at this problem? I am confused in working with Julia ode solver.

I want to use Julia solver for the chemical reaction below with k=0 and v=1 parameters. which literally that there is only one reaction (v, L1+R --> C0). But when I use the solver, it surprisingly giving an answer with increasing amount of L2. 

(k, v), L1 + R <--> C0
    
k, L2 --> D0
[mail.pdf](https://github.com/JuliaDiffEq/DiffEqBiological.jl/files/2090330/mail.pdf)

**Comment by ChrisRackauckas** [comment]
The code from the PDF is:

```julia
# two antigens and N=1 same K
rn = @reaction_network rtype begin
(k, ν1), L1 + R ↔ C0
k, L2 → D0
end k ν1
rnpar = [0, 1] # values of the rate constants
varlabels = ["L1", "L2", "R", "C0", "D0"]
tf = 1
u0f = [1., 0., 1, 0.,0.]
odeprob = ODEProblem(rn, u0f, (0.,tf),rnpar)
sol = solve(odeprob,Tsit5())
plot(sol, label=varlabels)
```

**Comment by ChrisRackauckas** [comment]
Oh the issue is that `varlabels` is incorrect. If you check:

```julia
> rn.syms
5-element Array{Symbol,1}:
 :L1
 :R
 :C0
 :L2
 :D0
```

The reason is because this is due to parser order: it reads the first line to find L1, R, and C0, then the next line for L2 then D0. The ModelingToolkit.jl way would let users set the ordering, but for now we can just document that it exists in `rn.syms`. So for example:

```julia
plot(sol, label=rn.syms)
```

![correct_labels](https://user-images.githubusercontent.com/1814174/41237886-8d80a7ae-6d49-11e8-851f-8cccb7d32d15.png)

**Comment by edsontag** [comment]
Thanks.  Just to make sure, you are saying that we should declare as follows:
_varlabels = ["L1", "R", "C0","L2", "D0"]
u0f = [1., 1, 0.,0.,0.]_
instead of what we have, right?
Would it matter if variables in the same equation are ermuted in declarations, let us say
_varlabels = ["R","L1","C0","L2", "D0"]_  ?
Should the parameters also follow a certain order?
Thanks again!

**Comment by ChrisRackauckas** [comment]
> Thanks. Just to make sure, you are saying that we should declare as follows:
> varlabels = ["L1", "R", "C0","L2", "D0"]
> u0f = [1., 1, 0.,0.,0.]
> instead of what we have, right?

Yes

>Would it matter if variables in the same equation are ermuted in declarations, let us say
>varlabels = ["R","L1","C0","L2", "D0"] ?

Internally it builds an ODE where it makes variable 1 the `L1` ODE, variable 2 the `R` ODE, etc. and it does this in the order that it finds the dependent variables. So no, you cannot change the order. We are working on that with a new foundation via ModelingToolkit.jl, but for now this is a limitation.

>Should the parameters also follow a certain order?

Yes, the parameters are defined in the order which you give them after the `end`, so `end k ν1` means `p[1] = k` and `p[2] = ν1`.

We should probably clarify these rules as part of the DSL's spec.
